# .github/workflows/deploy.yml

name: CI for product-create-service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: posgres
          POSTGRES_PASSWORD: dayana
          POSTGRES_DB: products_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run migrations (if any)
      run: |
        # Add your migration commands here, e.g.:
        # alembic upgrade head
        echo "No migrations specified"

    - name: Run tests
      run: |
        # Add your test command here, e.g. pytest
        echo "No tests implemented"

    - name: Run app (optional)
      run: |
        # Start app if you want to test it live (usually not done in CI)
        # uvicorn app.main:app --host 0.0.0.0 --port 3015 --reload
        echo "Build complete"
