version: '3.8'

services:
  product_delete_service:
    image: dayanaheredia/product_delete_by_name_service:latest
    container_name: product_delete_service_container
    ports:
      - "3019:3019"
    restart: unless-stopped

  product_get_by_name_service:
    image: dayanaheredia/product_get_by_name_service:latest
    container_name: product_get_by_name_service_container
    ports:
      - "3018:3018"
    restart: unless-stopped

  product_list_service:
    image: dayanaheredia/product_list_service:latest
    container_name: product_list_service_container
    ports:
      - "3017:3017"
    restart: unless-stopped

  product_update_service:
    image: dayanaheredia/product_update_service:latest
    container_name: product_update_service_container
    ports:
      - "3016:3016"
    restart: unless-stopped

  product_create_service:
    image: dayanaheredia/product_create_service:latest
    container_name: product_create_service_container
    ports:
      - "3015:3015"
    restart: unless-stopped

  user-create:
    image: dayanaheredia/user_create_service:latest
    ports:
      - "8000:8000"
    env_file:
      - ./userDomain/user_create_service/.env

  user-update:
    image: dayanaheredia/user-update-service:latest
    ports:
      - "3011:3011"
    env_file:
      - ./userDomain/user_update_service/.env

  user-get-by-id:
    image: dayanaheredia/user_get_id_service:latest
    ports:
      - "3014:3014"
    env_file:
      - ./userDomain/user_get_by_id_service/.env

  user-list:
    image: dayanaheredia/user_list_service:latest
    ports:
      - "3010:3010"
    env_file:
      - ./userDomain/user_list_service/.env

  user-delete:
    image: dayanaheredia/user-delete-service:latest
    ports:
      - "3012:3012"
    env_file:
      - ./userDomain/user_delete_service/.env

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway_container
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - product_delete_service
      - product_get_by_name_service
      - product_list_service
      - product_update_service
      - product_create_service
      - user-create
      - user-update
      - user-get-by-id
      - user-list
      - user-delete
