version: '3.8'

services:
  product_create_service:
    image: dayanaheredia/product_create_service:latest
    container_name: product_create_service_container
    ports:
      - "3015:3015"
    restart: unless-stopped
