FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY .env .env

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

EXPOSE 3017

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3017"]
