name: Deploy userDomain Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull images from Docker Hub
      run: |
        docker pull dayanaheredia/user_create_service:latest
        docker pull dayanaheredia/user-update-service:latest
        docker pull dayanaheredia/user_get_id_service:latest
        docker pull dayanaheredia/user_list_service:latest
        docker pull dayanaheredia/user-delete-service:latest

    - name: Start services with docker-compose
      run: |
        docker-compose up -d
