server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:users_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Dayana2000}
    driver-class-name: com.mysql.cj.jdbc.Driver

graphql:
  servlet:
    mapping: /graphql
    enabled: true

