version: '3.8'

services:
  user-create:
    image: dayanaheredia/user_create_service:latest
    ports:
      - "8000:8000"
    env_file:
      - ./user_create_service/.env

  user-update:
    image: dayanaheredia/user-update-service:latest
    ports:
      - "3011:3011"
    env_file:
      - ./user_update_service/.env

  user-get-by-id:
    image: dayanaheredia/user_get_id_service:latest
    ports:
      - "3014:3014"
    env_file:
      - ./user_get_by_id_service/.env

  user-list:
    image: dayanaheredia/user_list_service:latest
    ports:
      - "3010:3010"
    env_file:
      - ./user_list_service/.env

  user-delete:
    image: dayanaheredia/user-delete-service:latest
    ports:
      - "3012:3012"
    env_file:
      - ./user_delete_service/.env

  